# Generated by Django 5.0.6 on 2024-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Female')], max_length=6)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
