# Generated by Django 5.0.6 on 2024-05-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0002_alter_teacher_gender_alter_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='subject.subject'),
        ),
    ]
