# Generated by Django 5.0.6 on 2024-05-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0003_remove_pupil_level_pupil_gender_pupil_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='age',
        ),
    ]
