# Generated by Django 5.0.6 on 2024-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0004_remove_pupil_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='age',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='is_eligible_for_prefect',
            field=models.BooleanField(default=False),
        ),
    ]
